# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package LibreDWG;
use base qw(Exporter);
use base qw(DynaLoader);
package LibreDWGc;
bootstrap LibreDWG;
package LibreDWG;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package LibreDWG;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package LibreDWG;

*new_Dwg_Object_Array = *LibreDWGc::new_Dwg_Object_Array;
*delete_Dwg_Object_Array = *LibreDWGc::delete_Dwg_Object_Array;
*Dwg_Object_Array_getitem = *LibreDWGc::Dwg_Object_Array_getitem;
*Dwg_Object_Array_setitem = *LibreDWGc::Dwg_Object_Array_setitem;

# ------- VARIABLE STUBS --------

package LibreDWG;

1;
